export const dummyContacts = [
  {
    id: "23f97e0c-387d-4d54-aecc-9423595cbb55",
    contact_email: "test",
    first_name: "a",
    last_name: "a",
    birth_date: null,
    location: null,
    phone: null,
    company_name: null,
    company_website: null,
    industry: null,
    description: null,
    problem: null,
    solution: null,
    created_at: "2024-01-29T03:58:04.573348+00:00",
    created_by: null,
    reviews: null,
    job_title: null,
    interests: null,
    metadata: null,
    opener: null,
    person_linkedin_url: null,
  },
  {
    id: "6fa89893-4ff1-47e3-ac20-4208fbe648f7",
    contact_email: "b",
    first_name: null,
    last_name: null,
    birth_date: null,
    location: null,
    phone: null,
    company_name: null,
    company_website: null,
    industry: null,
    description: null,
    problem: null,
    solution: null,
    created_at: "2024-01-29T03:58:15.48658+00:00",
    created_by: null,
    reviews: null,
    job_title: null,
    interests: null,
    metadata: null,
    opener: null,
    person_linkedin_url: null,
  },
];
